import {
    createIcons,
    BadgePlus,
    Bug,
    CircleDollarSign,
    CircleHelp,
    CirclePlay,
    CircleStop,
    Download,
    ExternalLink,
    Github,
    Menu,
    Newspaper,
    PencilRuler,
    Share2,
    SquareChevronRight,
    SunMoon,
    UndoDot,
    Youtube,
    Link, 
} from 'lucide';

createIcons({
    icons: {
        BadgePlus,
        Bug,
        CircleDollarSign,
        CircleHelp,
        CirclePlay,
        CircleStop,
        Download,
        ExternalLink,
        Github,
        Link,
        Menu,
        Newspaper,
        PencilRuler,
        Share2,
        SquareChevronRight,
        SunMoon,
        UndoDot,
        Youtube
    },
});