name: UnitTests

on:
  push:
    branches: [ "main" ]

jobs:
  pgetinker-tests:

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install && npm run build && composer install --prefer-dist --no-interaction --no-progress && php artisan dusk:chrome-driver --detect

      - name: Copy environment file
        run: cp .env.example .env

      - name: Build Library Objects
        run: bash build-libs.sh
        
      - name: Generate app key
        run: php artisan key:generate

      - name: Create Database File
        run: touch database/database.sqlite
      
      - name: Initial Database Migration
        run: php artisan migrate
        
      - name: Execute Unit Tests
        run: php artisan test

      - name: Run Server
        run: php artisan serve &
      
      - name: Execute Browser Tests
        run: php artisan dusk
